### ISSUE TITLE
Atom author metadata gets "flattened"

### ISSUE THREAD

**Issue by gardnermj** [HBehrens/feedsanitizer#12]
If an Atom feed contains an &lt;author&gt; element with &lt;name&gt; and &lt;email&gt; metadata, like so:

``` html
<author>
  <name>Bob</name>
  <email>bob@example.com</email>
</author>
```

...it gets turned into this in the sanitized output:

``` html
<author>
  <name>Bob (bob@example.com)</name>
</author>
```

Feedsanitizer should keep the metadata separate, as in the original feed.

**Comment by HBehrens** [comment]
this is by intention since Atom and RSS use a different layout and I wanted to have a single layout in the end. What are you using the feedsanitzer for?

**Comment by gardnermj** [comment]
I was thinking of using a command-line version of it to sanitize feeds before running them through the RSS client I'm developing, in order to save me from having to deal with all of the crazy inconsistencies of real feeds myself. Because my client treats email addresses specially, it needs to know what the email address part of the author's "name" is (if there is one).

But I've since decided against using feedsanitizer-- I'll just deal with those kinds of issues myself (those that my parser library won't handle for me, anyway). Thanks for your time.

**Comment by HBehrens** [comment]
Allright, good luck!
